version: "3"
services:
  #PHP Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./backend:/var/www
    ports:
      - "9000:9000"
      - "5173:5173"
    networks:
      - network

  #Nginx Service
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network

  #MySQL Service
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "root"
      MYSQL_PASS: "root"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - network

#Docker Networks
networks:
  network:
    driver: bridge